### ISSUE TITLE
No validation on Query#start_time and #end_time if they are strings

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-python#22]
You can set start_time and end_time to whatever you want, as long as it is a string. We should check that it is a date, or not allow strings at all (as in all other clients).

``` python
>>> query.pattern = '"hello world"'
>>> query.start_time = "NOT_A_VALID_DATE"
>>> print query.url()
https://api.twingly.com/analytics/Analytics.ashx?tsTo=&searchpattern=%22hello+world%22&ts=NOT_A_VALID_DATE&xmloutputversion=2&key=<api-key>&documentlang=
>>>
```

**Comment by roback** [comment]
We should also raise an error [like we do in the ruby client](https://github.com/twingly/twingly-search-api-ruby/blob/master/lib/twingly/search/query.rb#L70-L74) when you try to set start_time/end_time to something other than a datetime object.

We don't have to wait for for the user to call `execute`, we can do the check when assigning, just as in ruby:

``` python
$ python
>>> class Query(object):
...     @property
...     def start_time(self):
...             return self._start_time
...     @start_time.setter
...     def start_time(self, value):
...             if value == "verboten":
...                     raise ValueError("Es ist verboten!")
...             self._start_time = value
...
>>> query = Query()
>>> query.start_time = "2016-04-01"
>>> print query.start_time
2016-04-01
>>> query.start_time = "verboten"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 8, in start_time
ValueError: Es ist verboten!
>>> print query.start_time
2016-04-01
>>>
```

Works in Python 2.7.11 at least :)
