### ISSUE TITLE
Cannot pip/easy_install twingly-search: missing README.md

### ISSUE THREAD

**Issue by wkoot** [twingly/twingly-search-api-python#30]
The README.md file cannot be opened when easy_install calls setup.py:

```
# easy_install twingly-search
Searching for twingly-search
Reading https://pypi.python.org/simple/twingly-search/
Best match: twingly-search 1.2.0
Downloading https://pypi.python.org/packages/af/f0/235ca0cc505ac92942f1c849dfe6ac19035d390cadb55899bad7c5e6c1c1/twingly-search-1.2.0.tar.gz#md5=adf322688ff961328daa7b7218e22302
Processing twingly-search-1.2.0.tar.gz
Writing /tmp/easy_install-VBkEyl/twingly-search-1.2.0/setup.cfg
Running twingly-search-1.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-VBkEyl/twingly-search-1.2.0/egg-dist-tmp-FWYFs6
error: README.md: No such file or directory
```

It's probably not a good idea to set the long_description to the contents of the readme file, but otherwise resolve the file path?

``` python
import os
file_directory = os.path.dirname(__file__) if "__file__" in globals() else os.getcwd()
readme_file = open(os.path.join(file_directory, 'README.md'), 'r')
```

**Comment by wkoot** [comment]
Doesn't work with pip either because the readme is missing from the tarball:

```
# pip install twingly-search
Downloading/unpacking twingly-search
  Downloading twingly-search-1.2.0.tar.gz
  Running setup.py egg_info for package twingly-search
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "build/twingly-search/setup.py", line 13, in <module>
        readme_file = open('README.md', 'r')
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "build/twingly-search/setup.py", line 13, in <module>

    readme_file = open('README.md', 'r')

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in build/twingly-search
Storing complete log in /root/.pip/pip.log
```

**Comment by walro** [comment]
Which pip version is that? It works with 8.1.2 which seems to be using the whl file instead, at least on OSX:

```
pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)

pip install twingly-search
Collecting twingly-search
  Downloading twingly_search-1.2.0-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python2.7/site-packages (from twingly-search)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/site-packages (from twingly-search)
Installing collected packages: twingly-search
Successfully installed twingly-search-1.2.0
```

But yeah, it should still work with `easy_install` and older versions of `pip` so we'll have to fix that.

**Comment by wkoot** [comment]
```
# pip --version
pip 1.1 from lib/python2.7/site-packages/pip-1.1-py2.7.egg (python 2.7)
# easy_install --version
setuptools 7.0
```

**Comment by walro** [comment]
I released 1.2.1 of twingly-search, at least I can install using `easy_install` on OSX now, give it a shot and let me know how it turns out.

**Comment by wkoot** [comment]
It works, tnx

**Comment by walro** [comment]
👍
