### ISSUE TITLE
Migrate to pypi.org

### ISSUE THREAD

**Issue by walro** [twingly/twingly-search-api-python#39]
As per https://packaging.python.org/guides/migrating-to-pypi-org/

To workaround that for now I did as they proposed:

> If for some reason you’re unable to upgrade the version of your tool to a version that defaults to using PyPI.org, then you may edit ~/.pypirc and include the repository: line, but use the value https://upload.pypi.org/legacy/ instead

**Comment by walro** [comment]
I think we need to setup our requirements file to ensure we run new enough stuff.

Next time we need to publish I propose we take a look at this again.

**Comment by walro** [comment]
I tried with the bare minimum changes, just dropped the "repository" line as per:

> Then simply delete the line starting with repository and you will use your upload tool’s default URL.

However, this emits a warning: `WARNING: Uploading via this command is deprecated, use twine to upload instead (https://pypi.org/p/twine/)` and it eventually fails with:

```
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    'Programming Language :: Python :: 3.5',
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/upload.py", line 26, in run
    orig.upload.run(self)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/upload.py", line 62, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/upload.py", line 133, in upload_file
    value = str(value).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 97: ordinal not in range(128)
```

I think we should probably switch to twine and then take it from there.
